export const MovieList = [
  {
    adult: false,
    backdrop_path: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
    genre_ids: [28, 12, 878],
    id: 505642,
    original_language: "en",
    original_title: "Black Panther: Wakanda Forever",
    overview:
      "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
    popularity: 2782.773,
    poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    release_date: "2022-11-09",
    title: "Black Panther: Wakanda Forever",
    video: false,
    vote_average: 7.4,
    vote_count: 3684,
  },
  {
    adult: false,
    backdrop_path: "/irwQcdjwtjLnaA0iErabab9PrmG.jpg",
    genre_ids: [28, 12, 53],
    id: 646389,
    original_language: "en",
    original_title: "Plane",
    overview:
      "After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.",
    popularity: 2266.231,
    poster_path: "/qi9r5xBgcc9KTxlOLjssEbDgO0J.jpg",
    release_date: "2023-01-12",
    title: "Plane",
    video: false,
    vote_average: 6.9,
    vote_count: 707,
  },
  {
    adult: false,
    backdrop_path: "/b1Y8SUb12gPHCSSSNlbX4nB3IKy.jpg",
    genre_ids: [16, 12, 35],
    id: 315162,
    original_language: "en",
    original_title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    popularity: 2378.726,
    poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    release_date: "2022-12-07",
    title: "Puss in Boots: The Last Wish",
    video: false,
    vote_average: 8.5,
    vote_count: 4128,
  },
  {
    adult: false,
    backdrop_path: "/ovM06PdF3M8wvKb06i4sjW3xoww.jpg",
    genre_ids: [878, 12, 28],
    id: 76600,
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    popularity: 1224.144,
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    release_date: "2022-12-14",
    title: "Avatar: The Way of Water",
    video: false,
    vote_average: 7.7,
    vote_count: 5546,
  },
  {
    adult: false,
    backdrop_path: "/3JSoB7eMbCd8sE8alxNiUtrNiTz.jpg",
    genre_ids: [12, 878, 35],
    id: 640146,
    original_language: "en",
    original_title: "Ant-Man and the Wasp: Quantumania",
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    popularity: 1025.636,
    poster_path: "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
    release_date: "2023-02-15",
    title: "Ant-Man and the Wasp: Quantumania",
    video: false,
    vote_average: 6.5,
    vote_count: 807,
  },
  {
    adult: false,
    backdrop_path: "/afsYFdid9pnnRd6tTrHFUbHgXJn.jpg",
    genre_ids: [878, 28, 12],
    id: 843794,
    original_language: "ko",
    original_title: "정이",
    overview:
      "On an uninhabitable 22nd-century Earth, the outcome of a civil war hinges on cloning the brain of an elite soldier to create a robot mercenary.",
    popularity: 764.299,
    poster_path: "/z2nfRxZCGFgAnVhb9pZO87TyTX5.jpg",
    release_date: "2023-01-20",
    title: "JUNG_E",
    video: false,
    vote_average: 6.3,
    vote_count: 349,
  },
  {
    adult: false,
    backdrop_path: "/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg",
    genre_ids: [28, 12, 14, 878],
    id: 19995,
    original_language: "en",
    original_title: "Avatar",
    overview:
      "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
    popularity: 592.036,
    poster_path: "/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
    release_date: "2009-12-15",
    title: "Avatar",
    video: false,
    vote_average: 7.6,
    vote_count: 28496,
  },
  {
    adult: false,
    backdrop_path: "/53BC9F2tpZnsGno2cLhzvGprDYS.jpg",
    genre_ids: [14, 28, 12, 53],
    id: 736526,
    original_language: "no",
    original_title: "Troll",
    overview:
      "Deep inside the mountain of Dovre, something gigantic awakens after being trapped for a thousand years. Destroying everything in its path, the creature is fast approaching the capital of Norway. But how do you stop something you thought only existed in Norwegian folklore?",
    popularity: 507.647,
    poster_path: "/9z4jRr43JdtU66P0iy8h18OyLql.jpg",
    release_date: "2022-12-01",
    title: "Troll",
    video: false,
    vote_average: 6.7,
    vote_count: 1245,
  },
  {
    adult: false,
    backdrop_path: "/pketzKFjq5TERXoXFM3L0OYRCLe.jpg",
    genre_ids: [16, 10751, 12, 35],
    id: 599019,
    original_language: "ru",
    original_title: "Большое путешествие. Специальная доставка",
    overview:
      "It has been a year since Mic Mic and Oscar returned from their incredible adventure. And now, after a diabolical plan by Vulture to sabotage the delivery of the Grizzly cub to his opponent in the American presidential elections, Mic Mic, Oscar, Panda teenager and Stork set off on another great adventure as they ride a zeppelin to return little Grizzly to its rightful parents and save the American elections and the whole continent from an erupting volcano.",
    popularity: 489.176,
    poster_path: "/dabXVfrAFfhDte8XVemom3mTJog.jpg",
    release_date: "2022-10-07",
    title: "Big Trip 2: Special Delivery",
    video: false,
    vote_average: 6.3,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: "/cU7itLM8qmwMiaNnWsJPQLKe79j.jpg",
    genre_ids: [878, 27, 12, 28],
    id: 1013870,
    original_language: "en",
    original_title: "Kids vs. Aliens",
    overview:
      "All Gary wants is to make awesome home movies with his best buds. All his older sister Samantha wants is to hang with the cool kids. When their parents head out of town one Halloween weekend, an all-time rager of a teen house party turns to terror when aliens attack, forcing the siblings to band together to survive the night.",
    popularity: 428.377,
    poster_path: "/wQ53sO5n9LCFbssV3oQ4CuajL1L.jpg",
    release_date: "2023-01-20",
    title: "Kids vs. Aliens",
    video: false,
    vote_average: 5.9,
    vote_count: 38,
  },
  {
    adult: false,
    backdrop_path: "/vXjpwkXPirBmgdEpIknfN8ziDD.jpg",
    genre_ids: [16, 12, 14, 35],
    id: 947938,
    original_language: "ru",
    original_title: "Мальчик-дельфин",
    overview:
      "When a plane crashes at sea, dolphins rescue a little boy and raise him as family. He lives a carefree life beneath the waves until an evil monster seizes power over the underwater world. The boy is banished to dry land, where a kind-hearted captain takes him in. With the captain’s help, the boy sets out on a journey to solve the mystery of his true identity.",
    popularity: 457.961,
    poster_path: "/gISoDEiaUH9BNEunmLC7FgUVaia.jpg",
    release_date: "2022-04-07",
    title: "Dolphin Boy",
    video: false,
    vote_average: 6.2,
    vote_count: 37,
  },
  {
    adult: false,
    backdrop_path: "/9iRRfMZbnpgHDdKi2lczGGYZXDo.jpg",
    genre_ids: [12, 10751, 14],
    id: 411,
    original_language: "en",
    original_title:
      "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    overview:
      "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
    popularity: 424.603,
    poster_path: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
    release_date: "2005-12-07",
    title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    video: false,
    vote_average: 7.1,
    vote_count: 9355,
  },
  {
    adult: false,
    backdrop_path: "/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity: 425.542,
    poster_path: "/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 8,
    vote_count: 16842,
  },
  {
    adult: false,
    backdrop_path: "/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg",
    genre_ids: [12, 28, 878],
    id: 299536,
    original_language: "en",
    original_title: "Avengers: Infinity War",
    overview:
      "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
    popularity: 305.313,
    poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    release_date: "2018-04-25",
    title: "Avengers: Infinity War",
    video: false,
    vote_average: 8.3,
    vote_count: 26404,
  },
  {
    adult: false,
    backdrop_path: "/hT9ZUwLN5tB2O7miBu1oIMJFqJT.jpg",
    genre_ids: [12, 28, 878],
    id: 507086,
    original_language: "en",
    original_title: "Jurassic World Dominion",
    overview:
      "Four years after the destruction of Isla Nublar, Biosyn operatives attempt to track down Maisie Lockwood, while Dr Ellie Sattler investigates a genetically engineered swarm of giant insects.",
    popularity: 342.654,
    poster_path: "/kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg",
    release_date: "2022-06-01",
    title: "Jurassic World Dominion",
    video: false,
    vote_average: 6.9,
    vote_count: 4487,
  },
  {
    adult: false,
    backdrop_path: "/qdFrqXYH6PtyAVlegub7bpoSgro.jpg",
    genre_ids: [16, 12, 35, 10751],
    id: 573171,
    original_language: "es",
    original_title: "Huevitos Congelados",
    overview:
      "Follow the adventures of Toto and his family, who will have to travel to the South Pole to fulfill their promise to return a polar bear and some Spanish penguins to their home. In order to fulfill the promise, they will have to overcome some obstacles that will teach them how important teamwork is.",
    popularity: 357.726,
    poster_path: "/gBBCBMXKzWRADtliUYfV69aVIcz.jpg",
    release_date: "2022-12-14",
    title: "A Frozen Rooster",
    video: false,
    vote_average: 8,
    vote_count: 235,
  },
  {
    adult: false,
    backdrop_path: "/nITzFbM1JS7WEvFjjGL0kCb2yPr.jpg",
    genre_ids: [16, 10751, 12],
    id: 1045944,
    original_language: "en",
    original_title: "The Boss Baby: Christmas Bonus",
    overview:
      "Christmas Eve takes a twisty turn when the Boss Baby accidentally swaps places with one of Santa's elves and gets stranded at the North Pole.",
    popularity: 297.391,
    poster_path: "/iMmMxF6f2OonUrXrHKBLSYAhXly.jpg",
    release_date: "2022-12-06",
    title: "The Boss Baby: Christmas Bonus",
    video: false,
    vote_average: 6.8,
    vote_count: 218,
  },
  {
    adult: false,
    backdrop_path: "/qjGrUmKW78MCFG8PTLDBp67S27p.jpg",
    genre_ids: [16, 28, 12, 14, 53],
    id: 635302,
    original_language: "ja",
    original_title: "劇場版「鬼滅の刃」無限列車編",
    overview:
      "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
    popularity: 324.898,
    poster_path: "/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
    release_date: "2020-10-16",
    title: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train",
    video: false,
    vote_average: 8.3,
    vote_count: 2956,
  },
  {
    adult: false,
    backdrop_path: "/5wDBVictj4wUYZ31gR5WzCM9dLD.jpg",
    genre_ids: [16, 10751, 12, 878],
    id: 877269,
    original_language: "en",
    original_title: "Strange World",
    overview:
      "A journey deep into an uncharted and treacherous land, where fantastical creatures await the legendary Clades—a family of explorers whose differences threaten to topple their latest, and by far most crucial, mission.",
    popularity: 311.352,
    poster_path: "/fHMqfsYyl3lskPK2RiFRwhzwuep.jpg",
    release_date: "2022-11-23",
    title: "Strange World",
    video: false,
    vote_average: 6.5,
    vote_count: 817,
  },
  {
    adult: false,
    backdrop_path: "/yEQqrW61rwNuVRHTjgHOAU4dXNE.jpg",
    genre_ids: [28, 12, 10751, 35],
    id: 675353,
    original_language: "en",
    original_title: "Sonic the Hedgehog 2",
    overview:
      "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
    popularity: 268.07,
    poster_path: "/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
    release_date: "2022-04-08",
    title: "Sonic the Hedgehog 2",
    video: false,
    vote_average: 7.6,
    vote_count: 3719,
  },
];
